import { ApplicationFailure } from '@temporalio/workflow';
import { asc, eq } from 'drizzle-orm';
import { createRecommendationWorkflowRepository, db, marketSignals, properties, type RecommendationWorkflowRepository } from 'database';
import { calculateRuleBasedPricing, createConfiguredAiPricingProvider, PRICING_PROMPT_VERSION, type AiPricingProvider, validateAiPricingRecommendation } from 'pricing';
import type { AiCallMetrics, PricingWorkflowData, PricingWorkflowRequest, PricingWorkflowStatus } from 'shared';
import { marketSignalSchema, propertySchema, type MarketSignal, type Property } from 'shared';

export type PricingFailureType = 'INVALID_REQUEST' | 'PROPERTY_NOT_FOUND' | 'VALIDATION_REJECTED' | 'PROVIDER_FAILURE' | 'PERSISTENCE_FAILURE';
const terminalFailure = (message: string, type: PricingFailureType) => ApplicationFailure.nonRetryable(message, type);
const transientFailure = (message: string, type: PricingFailureType) => ApplicationFailure.retryable(message, type);

export interface RentalDataRepository { findPropertyById(id: string): Promise<Property | undefined>; listMarketSignals(id: string): Promise<MarketSignal[]>; }
const asNumber = (value: string | number) => typeof value === 'number' ? value : Number(value);
const rentalDataRepository: RentalDataRepository = {
  async findPropertyById(id) { const [row] = await db.select().from(properties).where(eq(properties.id, id)).limit(1); return row ? propertySchema.parse({ ...row, base_price: asNumber(row.base_price), min_price: asNumber(row.min_price), max_price: asNumber(row.max_price), bathrooms: asNumber(row.bathrooms), current_occupancy_rate: asNumber(row.current_occupancy_rate), target_occupancy_rate: asNumber(row.target_occupancy_rate) }) : undefined; },
  async listMarketSignals(id) { const rows = await db.select().from(marketSignals).where(eq(marketSignals.property_id, id)).orderBy(asc(marketSignals.date)); return rows.map((row) => marketSignalSchema.parse({ ...row, competitor_avg_price: asNumber(row.competitor_avg_price), local_event_score: asNumber(row.local_event_score), seasonality_score: asNumber(row.seasonality_score), demand_score: asNumber(row.demand_score) })); },
};
export interface PricingActivityDependencies { rentalDataRepository: RentalDataRepository; repository: RecommendationWorkflowRepository; provider: AiPricingProvider; }
let dependencies: PricingActivityDependencies = { rentalDataRepository, repository: createRecommendationWorkflowRepository(), provider: createConfiguredAiPricingProvider() };
export function setPricingActivityDependencies(next: Partial<PricingActivityDependencies>): void { dependencies = { ...dependencies, ...next }; }
export async function resolvePricingRequest(request: PricingWorkflowRequest, workflowId: string) { try { return await dependencies.repository.createOrResolve(request, workflowId); } catch { throw transientFailure('Pricing request persistence failed.', 'PERSISTENCE_FAILURE'); } }
export async function markPricingStatus(request: PricingWorkflowRequest, status: PricingWorkflowStatus, issueCodes: string[] = []) { try { await dependencies.repository.updateStatus(request, status, issueCodes); } catch { throw transientFailure('Pricing request persistence failed.', 'PERSISTENCE_FAILURE'); } }
export async function loadPricingData(request: PricingWorkflowRequest): Promise<Omit<PricingWorkflowData, 'deterministic'>> { try { const property = await dependencies.rentalDataRepository.findPropertyById(request.property_id); if (!property) throw terminalFailure('Property not found.', 'PROPERTY_NOT_FOUND'); return { property, signals: await dependencies.rentalDataRepository.listMarketSignals(request.property_id) }; } catch (error) { if (error instanceof ApplicationFailure) throw error; throw transientFailure('Pricing data load failed.', 'PERSISTENCE_FAILURE'); } }
export async function calculatePricing(data: Omit<PricingWorkflowData, 'deterministic'>): Promise<PricingWorkflowData> { try { return { ...data, deterministic: calculateRuleBasedPricing(data.property, data.signals) }; } catch { throw terminalFailure('Pricing request is invalid.', 'INVALID_REQUEST'); } }
export async function callPricingAi(request: PricingWorkflowRequest, deterministic: PricingWorkflowData['deterministic']): Promise<{ output: unknown; metrics: AiCallMetrics }> { const started = Date.now(); try { if (dependencies.provider.getRecommendationWithMetrics) { const result = await dependencies.provider.getRecommendationWithMetrics(deterministic); return { output: result.recommendation, metrics: result.metrics }; } const output = await dependencies.provider.getRecommendation(deterministic); return { output, metrics: { model: 'unknown', prompt_version: PRICING_PROMPT_VERSION, input_tokens: null, output_tokens: null, estimated_cost_usd: null, latency_ms: Date.now() - started, success: true } }; } catch { try { await dependencies.repository.saveMetrics(request, { model: 'unknown', prompt_version: PRICING_PROMPT_VERSION, input_tokens: null, output_tokens: null, estimated_cost_usd: null, latency_ms: Date.now() - started, success: false }); } catch { /* Failure metrics are best-effort and must not replace the retryable provider failure. */ } throw transientFailure('AI provider failed.', 'PROVIDER_FAILURE'); } }
export async function validatePricingAi(data: PricingWorkflowData, output: unknown) { return validateAiPricingRecommendation(data.property, data.deterministic, output); }
export async function persistAcceptedPricing(request: PricingWorkflowRequest, data: PricingWorkflowData, metadata: Parameters<RecommendationWorkflowRepository['saveAccepted']>[2]) { try { return await dependencies.repository.saveAccepted(request, data.deterministic, metadata); } catch { throw transientFailure('Recommendation persistence failed.', 'PERSISTENCE_FAILURE'); } }
export async function recordPricingMetrics(request: PricingWorkflowRequest, metrics: AiCallMetrics, recommendationId?: string) { try { await dependencies.repository.saveMetrics(request, metrics, recommendationId); } catch { throw transientFailure('Metrics persistence failed.', 'PERSISTENCE_FAILURE'); } }
