import { and, eq } from 'drizzle-orm';
import { db } from './client.js';
import { aiCallMetrics, pricingRecommendations, pricingWorkflowRequests } from './schema/index.js';
import type { AiCallMetrics, AiPricingRecommendation, PricingWorkflowRequest, PricingWorkflowStatus, PricingWorkflowStatusResult, RuleBasedPricingResult } from 'shared';

export interface RecommendationWorkflowRepository {
  createOrResolve(request: PricingWorkflowRequest, workflowId: string): Promise<{ id: string; workflow_id: string; status: PricingWorkflowStatus; existing: boolean }>;
  updateStatus(request: PricingWorkflowRequest, status: PricingWorkflowStatus, issueCodes?: string[]): Promise<void>;
  saveAccepted(request: PricingWorkflowRequest, deterministic: RuleBasedPricingResult, metadata: AiPricingRecommendation): Promise<string>;
  saveMetrics(request: PricingWorkflowRequest, metrics: AiCallMetrics, recommendationId?: string): Promise<void>;
  getStatus(request: PricingWorkflowRequest): Promise<PricingWorkflowStatusResult | undefined>;
}
const number = (value: string | number | null): number | null => value === null ? null : typeof value === 'number' ? value : Number(value);
export function createRecommendationWorkflowRepository(): RecommendationWorkflowRepository {
 return {
  async createOrResolve(request, workflowId) { const inserted = await db.insert(pricingWorkflowRequests).values({ property_id: request.property_id, pricing_date: request.pricing_date, temporal_workflow_id: workflowId }).onConflictDoNothing().returning(); const row = inserted[0] ?? (await db.select().from(pricingWorkflowRequests).where(and(eq(pricingWorkflowRequests.property_id, request.property_id), eq(pricingWorkflowRequests.pricing_date, request.pricing_date))).limit(1))[0]; if (!row) throw new Error('Unable to resolve workflow request.'); return { id: row.id, workflow_id: row.temporal_workflow_id, status: row.status, existing: inserted.length === 0 }; },
  async updateStatus(request, status, issueCodes = []) { await db.update(pricingWorkflowRequests).set({ status, issue_codes: issueCodes, updated_at: new Date() }).where(and(eq(pricingWorkflowRequests.property_id, request.property_id), eq(pricingWorkflowRequests.pricing_date, request.pricing_date))); },
  async saveAccepted(request, deterministic, metadata) { const [requestRow] = await db.select().from(pricingWorkflowRequests).where(and(eq(pricingWorkflowRequests.property_id, request.property_id), eq(pricingWorkflowRequests.pricing_date, request.pricing_date))).limit(1); if (!requestRow) throw new Error('Workflow request does not exist.'); const [row] = await db.insert(pricingRecommendations).values({ request_id: requestRow.id, property_id: request.property_id, pricing_date: request.pricing_date, deterministic_result: deterministic, deterministic_price: String(deterministic.recommended_price), minimum_price: String(deterministic.minimum_recommended_price), maximum_price: String(deterministic.maximum_recommended_price), explanation: metadata.explanation, confidence_score: String(metadata.confidence_score), risk_level: metadata.risk_level }).onConflictDoNothing().returning(); return row?.id ?? (await db.select().from(pricingRecommendations).where(eq(pricingRecommendations.request_id, requestRow.id)).limit(1))[0]!.id; },
  async saveMetrics(request, metrics, recommendationId) { const [row] = await db.select().from(pricingWorkflowRequests).where(and(eq(pricingWorkflowRequests.property_id, request.property_id), eq(pricingWorkflowRequests.pricing_date, request.pricing_date))).limit(1); if (!row) throw new Error('Workflow request does not exist.'); await db.insert(aiCallMetrics).values({ request_id: row.id, recommendation_id: recommendationId, model: metrics.model, prompt_version: metrics.prompt_version, input_tokens: metrics.input_tokens, output_tokens: metrics.output_tokens, estimated_cost_usd: metrics.estimated_cost_usd === null ? null : String(metrics.estimated_cost_usd), latency_ms: metrics.latency_ms, success: metrics.success ? 1 : 0 }); },
  async getStatus(request) { const [row] = await db.select().from(pricingWorkflowRequests).where(and(eq(pricingWorkflowRequests.property_id, request.property_id), eq(pricingWorkflowRequests.pricing_date, request.pricing_date))).limit(1); if (!row) return undefined; const [rec] = await db.select().from(pricingRecommendations).where(eq(pricingRecommendations.request_id, row.id)).limit(1); const [metrics] = await db.select().from(aiCallMetrics).where(eq(aiCallMetrics.request_id, row.id)).limit(1); return { property_id: row.property_id, pricing_date: row.pricing_date, workflow_id: row.temporal_workflow_id, status: row.status, issue_codes: row.issue_codes as never[], recommendation: rec && rec.deterministic_result ? { deterministic: rec.deterministic_result as RuleBasedPricingResult, ai_metadata: { recommended_price: number(rec.deterministic_price)!, explanation: rec.explanation, confidence_score: number(rec.confidence_score)!, risk_level: rec.risk_level as 'low'|'medium'|'high' } } : null, metrics: metrics ? { model: metrics.model, prompt_version: metrics.prompt_version, input_tokens: metrics.input_tokens, output_tokens: metrics.output_tokens, estimated_cost_usd: number(metrics.estimated_cost_usd), latency_ms: metrics.latency_ms, success: metrics.success === 1 } : null }; }
 }; }
