import { and, desc, eq } from 'drizzle-orm';
import { db } from './client.js';
import { aiCallMetrics, pricingRecommendations, pricingWorkflowRequests } from './schema/index.js';
import type { AiCallMetrics, AiPricingRecommendation, DashboardRecommendation, DashboardSummary, PricingWorkflowRequest, PricingWorkflowStatus, PricingWorkflowStatusResult, RuleBasedPricingResult } from 'shared';
import { properties } from './schema/index.js';

export interface RecommendationWorkflowRepository {
  createOrResolve(request: PricingWorkflowRequest, workflowId: string): Promise<{ id: string; workflow_id: string; status: PricingWorkflowStatus; existing: boolean }>;
  updateStatus(request: PricingWorkflowRequest, status: PricingWorkflowStatus, issueCodes?: string[], failureCode?: string): Promise<void>;
  saveAccepted(request: PricingWorkflowRequest, deterministic: RuleBasedPricingResult, metadata: AiPricingRecommendation): Promise<string>;
  saveMetrics(request: PricingWorkflowRequest, metrics: AiCallMetrics, recommendationId?: string): Promise<void>;
  getStatus(request: PricingWorkflowRequest): Promise<PricingWorkflowStatusResult | undefined>;
  listAcceptedRecommendations(): Promise<DashboardRecommendation[]>;
  getDashboardSummary(): Promise<DashboardSummary>;
}
const number = (value: string | number | null): number | null => value === null ? null : typeof value === 'number' ? value : Number(value);
export function createRecommendationWorkflowRepository(): RecommendationWorkflowRepository {
 return {
  async createOrResolve(request, workflowId) { const inserted = await db.insert(pricingWorkflowRequests).values({ property_id: request.property_id, pricing_date: request.pricing_date, temporal_workflow_id: workflowId }).onConflictDoNothing().returning(); const row = inserted[0] ?? (await db.select().from(pricingWorkflowRequests).where(and(eq(pricingWorkflowRequests.property_id, request.property_id), eq(pricingWorkflowRequests.pricing_date, request.pricing_date))).limit(1))[0]; if (!row) throw new Error('Unable to resolve workflow request.'); return { id: row.id, workflow_id: row.temporal_workflow_id, status: row.status, existing: inserted.length === 0 }; },
  async updateStatus(request, status, issueCodes = [], failureCode) { await db.update(pricingWorkflowRequests).set({ status, issue_codes: issueCodes, failure_code: failureCode ?? null, updated_at: new Date() }).where(and(eq(pricingWorkflowRequests.property_id, request.property_id), eq(pricingWorkflowRequests.pricing_date, request.pricing_date))); },
  async saveAccepted(request, deterministic, metadata) { const [requestRow] = await db.select().from(pricingWorkflowRequests).where(and(eq(pricingWorkflowRequests.property_id, request.property_id), eq(pricingWorkflowRequests.pricing_date, request.pricing_date))).limit(1); if (!requestRow) throw new Error('Workflow request does not exist.'); const [row] = await db.insert(pricingRecommendations).values({ request_id: requestRow.id, property_id: request.property_id, pricing_date: request.pricing_date, deterministic_result: deterministic, deterministic_price: String(deterministic.recommended_price), minimum_price: String(deterministic.minimum_recommended_price), maximum_price: String(deterministic.maximum_recommended_price), explanation: metadata.explanation, confidence_score: String(metadata.confidence_score), risk_level: metadata.risk_level }).onConflictDoNothing().returning(); return row?.id ?? (await db.select().from(pricingRecommendations).where(eq(pricingRecommendations.request_id, requestRow.id)).limit(1))[0]!.id; },
  async saveMetrics(request, metrics, recommendationId) { const [row] = await db.select().from(pricingWorkflowRequests).where(and(eq(pricingWorkflowRequests.property_id, request.property_id), eq(pricingWorkflowRequests.pricing_date, request.pricing_date))).limit(1); if (!row) throw new Error('Workflow request does not exist.'); await db.insert(aiCallMetrics).values({ request_id: row.id, recommendation_id: recommendationId, model: metrics.model, prompt_version: metrics.prompt_version, input_tokens: metrics.input_tokens, output_tokens: metrics.output_tokens, estimated_cost_usd: metrics.estimated_cost_usd === null ? null : String(metrics.estimated_cost_usd), latency_ms: metrics.latency_ms, success: metrics.success ? 1 : 0 }); },
  async getStatus(request) { const [row] = await db.select().from(pricingWorkflowRequests).where(and(eq(pricingWorkflowRequests.property_id, request.property_id), eq(pricingWorkflowRequests.pricing_date, request.pricing_date))).limit(1); if (!row) return undefined; const [rec] = await db.select().from(pricingRecommendations).where(eq(pricingRecommendations.request_id, row.id)).limit(1); const [acceptedMetrics] = rec ? await db.select().from(aiCallMetrics).where(and(eq(aiCallMetrics.recommendation_id, rec.id), eq(aiCallMetrics.success, 1))).orderBy(desc(aiCallMetrics.created_at), desc(aiCallMetrics.id)).limit(1) : []; const [metrics] = acceptedMetrics ? [acceptedMetrics] : await db.select().from(aiCallMetrics).where(eq(aiCallMetrics.request_id, row.id)).orderBy(desc(aiCallMetrics.created_at), desc(aiCallMetrics.id)).limit(1); return { property_id: row.property_id, pricing_date: row.pricing_date, workflow_id: row.temporal_workflow_id, status: row.status, issue_codes: row.issue_codes as never[], recommendation: rec && rec.deterministic_result ? { deterministic: rec.deterministic_result as RuleBasedPricingResult, ai_metadata: { recommended_price: number(rec.deterministic_price)!, explanation: rec.explanation, confidence_score: number(rec.confidence_score)!, risk_level: rec.risk_level as 'low'|'medium'|'high' } } : null, metrics: metrics ? { model: metrics.model, prompt_version: metrics.prompt_version, input_tokens: metrics.input_tokens, output_tokens: metrics.output_tokens, estimated_cost_usd: number(metrics.estimated_cost_usd), latency_ms: metrics.latency_ms, success: metrics.success === 1 } : null }; }
  ,async listAcceptedRecommendations() { const rows = await db.select({ rec: pricingRecommendations, property: properties }).from(pricingRecommendations).innerJoin(properties, eq(pricingRecommendations.property_id, properties.id)).orderBy(desc(pricingRecommendations.created_at)); const metricsByRecommendation = new Map<string, typeof aiCallMetrics.$inferSelect>(); for (const row of rows) { const [metric] = await db.select().from(aiCallMetrics).where(and(eq(aiCallMetrics.recommendation_id, row.rec.id), eq(aiCallMetrics.success, 1))).orderBy(desc(aiCallMetrics.created_at), desc(aiCallMetrics.id)).limit(1); if (metric) metricsByRecommendation.set(row.rec.id, metric); } return rows.map(({ rec, property }) => { const metric = metricsByRecommendation.get(rec.id); return { id: rec.id, property_id: rec.property_id, property_name: property.name, city: property.city, pricing_date: rec.pricing_date, base_price: Number(property.base_price), recommended_price: Number(rec.deterministic_price), minimum_price: Number(rec.minimum_price), maximum_price: Number(rec.maximum_price), explanation: rec.explanation, confidence_score: Number(rec.confidence_score), risk_level: rec.risk_level as 'low' | 'medium' | 'high', validation_status: rec.validation_status, estimated_cost_usd: metric ? number(metric.estimated_cost_usd) : null, latency_ms: metric?.latency_ms ?? null, created_at: rec.created_at.toISOString() }; }); }
  ,async getDashboardSummary() { const [requests, failed, metrics] = await Promise.all([db.select().from(pricingWorkflowRequests), db.select({ request: pricingWorkflowRequests, property: properties }).from(pricingWorkflowRequests).leftJoin(properties, eq(pricingWorkflowRequests.property_id, properties.id)).where(eq(pricingWorkflowRequests.status, 'failed')).orderBy(desc(pricingWorkflowRequests.updated_at)).limit(5), db.select().from(aiCallMetrics)]); const successful = metrics.filter((metric) => metric.success === 1); const latency = successful.length ? Math.round(successful.reduce((total, metric) => total + metric.latency_ms, 0) / successful.length) : null; const costs = metrics.map((metric) => number(metric.estimated_cost_usd)).filter((cost): cost is number => cost !== null); const accepted = requests.filter((request) => request.status === 'accepted').length; const rejected = requests.filter((request) => request.status === 'rejected').length; const completedValidation = accepted + rejected; return { total_workflow_requests: requests.length, accepted_recommendations: accepted, failed_workflows: requests.filter((request) => request.status === 'failed').length, validation_rejections: rejected, validation_pass_rate: completedValidation ? Number((accepted / completedValidation).toFixed(4)) : null, average_ai_latency_ms: latency, estimated_ai_cost_usd: costs.length ? Number(costs.reduce((total, cost) => total + cost, 0).toFixed(6)) : null, recent_failed_workflows: failed.map(({ request, property }) => ({ property_id: request.property_id, property_name: property?.name ?? null, pricing_date: request.pricing_date, status: 'failed' as const, failure_code: request.failure_code, failed_at: request.updated_at.toISOString() })) }; }
 }; }
